apiVersion: v1
kind: Pod
metadata:
  namespace: test-simple
  name: coap
  labels:
    env: coap
spec:
  nodeSelector:
    kubernetes.io/hostname: worker1
  containers:
  - name: coap-container
    image: usman476/coap:latest
    command: [ "python3" ]
    args: [ "coap-server.py" ]
    imagePullPolicy: IfNotPresent
    resources:
      limits:
        cpu: 20m
        memory: 20Mi
      requests:
        cpu: 10m
        memory: 10Mi
